### ISSUE TITLE
CI Not Failing 

### ISSUE THREAD

**Issue by vkochhar-dev** [a11ywatch/github-actions#54]
`Run a11ywatch/github-actions@v2
  with:
    WEBSITE_URL: http://localhost:9000
    SUBDOMAINS: false
    TLD: false
    FAIL_ERRORS_COUNT: 0
    LIST: true
    UPGRADE: true
    FIX: false
    EXTERNAL: false
    SITE_WIDE: false
    SITEMAP: false
    RECORD: false
    FAIL_TOTAL_COUNT: 0
    FAIL_WARNINGS_COUNT: 0
    DISABLE_PR_STATS: false
    SLIM: true`

The above comes from the logs after I run my action. The actions log contain:

{"accessScore":90,"errorCount":4,"issueMeta":{"missingAltCount":null,"skipContentIncluded":true},"noticeCount":0,"totalIssues":13,"warningCount":9},"lastScanDate":"2023-09-29T10:55:11.582Z","online":true,"pageLoadTime":{"duration":245,"durationFormated":"Lightning Fast"},"url":"http://localhost:9000"},"message":"Scan completed in 1.25735276s","success":true}

Which shows that there are axe errors in the application but the job still passes and doesn't fail

**Comment by j-mendez** [comment]
Hi @vkochhar-dev set the fail error count to a value greater than 0. 0 will prevent the CI from failing. Try to use 1 for immediate failures.

**Comment by vkochhar-dev** [comment]
Hi @j-mendez perfect thanks for the quick response. I have implemented the fix and it is all working as expected thanks!

**Comment by j-mendez** [comment]
@vkochhar-dev You are welcome, I pushed up a change adding the note for the failure counter https://github.com/a11ywatch/github-actions/commit/bd2146961cff492352a72c329e3b203a4cd77379. Thank you for the issue!
